NAME = ex00

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS_FILES = \
	main.cpp \
	newZombie.cpp \
	Zombie.cpp \
	randomChump.cpp \

OBJS = $(SRCS_FILES:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	@$(CC) $(CFLAGS) -o $(NAME) $(OBJS)

%.o: %.c
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	@rm -f $(OBJS)

fclean: clean
	@rm -f $(NAME)
	
re: fclean all

.PHONY: all clean fclean re
